-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local _T = {}

_T.TESTINT64 = protobuf.Descriptor();
_T.TESTINT64_ID1_FIELD = protobuf.FieldDescriptor();
_T.TESTINT64_ID2_FIELD = protobuf.FieldDescriptor();
_T.TESTINT64_ID3_FIELD = protobuf.FieldDescriptor();
_T.TESTINT64_ID4_FIELD = protobuf.FieldDescriptor();
_T.TESTINT64_ID5_FIELD = protobuf.FieldDescriptor();
_T.LOGINGAME_C2S_MSG = protobuf.Descriptor();
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD = protobuf.FieldDescriptor();

_T.TESTINT64_ID1_FIELD.name = "id1"
_T.TESTINT64_ID1_FIELD.full_name = ".TestInt64.id1"
_T.TESTINT64_ID1_FIELD.number = 1
_T.TESTINT64_ID1_FIELD.index = 0
_T.TESTINT64_ID1_FIELD.label = 2
_T.TESTINT64_ID1_FIELD.has_default_value = false
_T.TESTINT64_ID1_FIELD.default_value = 0
_T.TESTINT64_ID1_FIELD.type = 3
_T.TESTINT64_ID1_FIELD.cpp_type = 2

_T.TESTINT64_ID2_FIELD.name = "id2"
_T.TESTINT64_ID2_FIELD.full_name = ".TestInt64.id2"
_T.TESTINT64_ID2_FIELD.number = 2
_T.TESTINT64_ID2_FIELD.index = 1
_T.TESTINT64_ID2_FIELD.label = 2
_T.TESTINT64_ID2_FIELD.has_default_value = false
_T.TESTINT64_ID2_FIELD.default_value = 0
_T.TESTINT64_ID2_FIELD.type = 4
_T.TESTINT64_ID2_FIELD.cpp_type = 4

_T.TESTINT64_ID3_FIELD.name = "id3"
_T.TESTINT64_ID3_FIELD.full_name = ".TestInt64.id3"
_T.TESTINT64_ID3_FIELD.number = 3
_T.TESTINT64_ID3_FIELD.index = 2
_T.TESTINT64_ID3_FIELD.label = 2
_T.TESTINT64_ID3_FIELD.has_default_value = false
_T.TESTINT64_ID3_FIELD.default_value = 0
_T.TESTINT64_ID3_FIELD.type = 18
_T.TESTINT64_ID3_FIELD.cpp_type = 2

_T.TESTINT64_ID4_FIELD.name = "id4"
_T.TESTINT64_ID4_FIELD.full_name = ".TestInt64.id4"
_T.TESTINT64_ID4_FIELD.number = 4
_T.TESTINT64_ID4_FIELD.index = 3
_T.TESTINT64_ID4_FIELD.label = 2
_T.TESTINT64_ID4_FIELD.has_default_value = false
_T.TESTINT64_ID4_FIELD.default_value = 0
_T.TESTINT64_ID4_FIELD.type = 6
_T.TESTINT64_ID4_FIELD.cpp_type = 4

_T.TESTINT64_ID5_FIELD.name = "id5"
_T.TESTINT64_ID5_FIELD.full_name = ".TestInt64.id5"
_T.TESTINT64_ID5_FIELD.number = 5
_T.TESTINT64_ID5_FIELD.index = 4
_T.TESTINT64_ID5_FIELD.label = 2
_T.TESTINT64_ID5_FIELD.has_default_value = false
_T.TESTINT64_ID5_FIELD.default_value = 0
_T.TESTINT64_ID5_FIELD.type = 16
_T.TESTINT64_ID5_FIELD.cpp_type = 2

_T.TESTINT64.name = "TestInt64"
_T.TESTINT64.full_name = ".TestInt64"
_T.TESTINT64.nested_types = {}
_T.TESTINT64.enum_types = {}
_T.TESTINT64.fields = {_T.TESTINT64_ID1_FIELD, _T.TESTINT64_ID2_FIELD, _T.TESTINT64_ID3_FIELD, _T.TESTINT64_ID4_FIELD, _T.TESTINT64_ID5_FIELD}
_T.TESTINT64.is_extendable = false
_T.TESTINT64.extensions = {}
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.name = "token"
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.full_name = ".LoginGame_C2S_Msg.token"
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.number = 1
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.index = 0
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.label = 2
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.has_default_value = false
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.default_value = ""
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.type = 9
_T.LOGINGAME_C2S_MSG_TOKEN_FIELD.cpp_type = 9

_T.LOGINGAME_C2S_MSG.name = "LoginGame_C2S_Msg"
_T.LOGINGAME_C2S_MSG.full_name = ".LoginGame_C2S_Msg"
_T.LOGINGAME_C2S_MSG.nested_types = {}
_T.LOGINGAME_C2S_MSG.enum_types = {}
_T.LOGINGAME_C2S_MSG.fields = {_T.LOGINGAME_C2S_MSG_TOKEN_FIELD}
_T.LOGINGAME_C2S_MSG.is_extendable = false
_T.LOGINGAME_C2S_MSG.extensions = {}

_T.LoginGame_C2S_Msg = protobuf.Message(_T.LOGINGAME_C2S_MSG)
_T.TestInt64 = protobuf.Message(_T.TESTINT64)

return _T